AWSTemplateFormatVersion: '2010-09-09'

Description: >
  EC2 Nested Stack

Parameters:
  ImageId:
    Description: AMI ID
    Type: String

Resources:
  NestedEc2Role: #IAM Role for EC2
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: /   
  Ec2InstanceProfile: #Instance Profile for ec2
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - Ref: NestedEc2Role
  InstanceSecurityGroup: #Security Group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: vpc-0dcb2a5f09b8a5093
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyInstance: #EC2 Instance
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: ImageId
      IamInstanceProfile: 
        Ref: Ec2InstanceProfile
      InstanceType: t2.micro
      KeyName: ami_key_pair
      SecurityGroupIds:
        - Fn::GetAtt:
          - InstanceSecurityGroup
          - GroupId
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install cloud-init
            sudo amazon-linux-extras install nginx1 -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
        
