AWSTemplateFormatVersion: '2010-09-09'

Description: >
  EC2 Root Stack

Parameters:
  ImageId:
    Description: AMI ID
    Type: String

Resources:
  RootStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ec2-nesed-stack-bucket.s3.ap-south-1.amazonaws.com/ec2.yml
      Parameters:
        ImageId: 
          Ref: ImageId

Outputs:
  stackoutput:
    Value:
      Ref: RootStack